<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>cn.iocoder.cloud</groupId>
        <artifactId>yudao</artifactId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <modules>
        <module>yudao-module-oa-api</module>
        <module>yudao-module-oa-server</module>
    </modules>
    <artifactId>yudao-module-oa</artifactId>
    <packaging>pom</packaging>

    <name>${project.artifactId}</name>
    <description>
        oa 包下，办公自动化（Office Automation）。
        例如说：日程、工作计划、笔记、通讯录、内部邮件和讨论区等等
    </description>

</project>
